### ISSUE TITLE
ImportError helper

### ISSUE THREAD

**Issue by richardbrinkman** [fwsmit/osm-knooppunten#5]
When I run `python3 knooppunten.py` I get:

> Traceback (most recent call last):
>  File "knooppunten.py", line 2, in <module>
>    from import_geojson import import_geojson, export_geojson
>  File "/home/brinkman/bin/osm-knooppunten/import_geojson.py", line 6, in <module>
>    from helper import is_number_valid
> ImportError: cannot import name 'is_number_valid'

I'm using helper version 2.5.0

**Comment by fwsmit** [comment]
Ah I didn't know helper was a python package as well. It's supposed to import the local file. I will make a quick fix, but I'll have to do it more properly later
